WORLD_ID = "WORLD__FOREX"
DOMAIN_IDS = (
    "DOMAIN__CURRENCY_PAIRS", "DOMAIN__CRYPTO_PAIRS", "DOMAIN__CROSS_STRENGTH",
    "DOMAIN__PAIR_RELATIONS", "DOMAIN__MARKET_REGIMES",
)
LEGACY_INPUT_IDS = ("DOMAIN__CURRENCY_SERIES_LEGACY", "DOMAIN__CRYPTO_SERIES_LEGACY")
